config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'homepage#index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  resources :users, path: '' do
    resources :posts, path: ''
  end

end

app/models/convert_markdown.rb
class ConvertMarkdown
  def perform(post_id)
    @post = Post.find(post_id)
    return unless @post

    @post.html = Octokit.markdown(@post.markdown, format: 'gfm')

    @post.save!
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :scoped, scope: :user

  belongs_to :user

  after_save :convert_markdown

  def convert_markdown
    ConvertMarkdown.new.perform(id) if markdown_changed?
  end

  def published?
    published_at.present?
  end

  def draft?
    !published?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login

  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = @user.posts.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_post_path(@user, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.friendly.find(params[:user_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @user.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :markdown)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/elements/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "Prog Blog", defined?(root_path) ? root_path : "#", class: "navbar-brand"
  / Collect the nav links, forms, and other content for toggling
  #navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
    %ul.nav.navbar-nav.navbar-right
      - if defined?(Devise)
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Edit Account", edit_user_registration_path
              %li.divider
              %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path
  / /.navbar-collapse

app/views/homepage/index.html.haml
.row
  .col-md-6
    = image_tag "progblog-cropped.png", style: 'width: 100%'
  .col-md-6
    %h1 The Easiest Blog Tool for Programmers
    %p Start your programming blog today for free
    %h2 Features
    %ul
      %li Use what you already know - Github Flavored Markdown - to format your source code snippets
      %li Don't worry about design - we provide a beautiful selection of templates to make your blog look great
      %li It's 100% free to use!
      %li Run your blog on your own domain
      %li= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProgBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
    = viewport_meta_tag(maximum_scale: '1.0')
  %body
    .container
      = render "elements/navbar"
      = bootstrap_flash
      = yield

app/views/posts/_form.html.haml
= form_for [@user, @post], html: { class: 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :title, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :title, class: 'text-field form-control'
  .form-group
    = f.label :markdown, class: 'control-label col-md-2'
    .col-md-10
      = f.text_area :markdown, class: 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), user_posts_path(@user), class: 'btn btn-default'

app/views/posts/_post.html.haml
%li
  = content_tag_for :div, post do
    = link_to post.title, edit_user_post_path(@user, post)
    %small
      - if post.published?
        published
        = time_ago_in_words post.published_at
        ago
      - else
        created
        = time_ago_in_words post.created_at
        ago

app/views/posts/edit.html.haml
.page-header
  %h1= t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: Post
= render 'form'

app/views/posts/index.html.haml
.page-header
  %h1= t '.title', default: Post

.published
  %h2 Published
  %ul
    - @posts.each do |post|
      - if post.published?
        = render post

.drafts
  %h2 Drafts
  %ul
    - @posts.each do |post|
      - if post.draft?
        = render post

= link_to t('.new', default: t("helpers.links.new")), new_user_post_path(@user), class: 'btn btn-primary'

app/views/posts/new.html.haml
- model_class = Post
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Post
= render :partial => 'form'

app/views/posts/show.html.haml
.page-header
  %h1= @post.title

%article
  != preserve @post.html.to_s